# Generated by Django 3.1.1 on 2020-09-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20200921_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('subject', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=15)),
                ('referer', models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('nairaland', 'Nairaland'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('', 'Please Choose')], default='', max_length=30, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
